services:
  evently.api:
    image: ${DOCKER_REGISTRY-}eventlyapi
    container_name: Evently.Api
    build:
      context: .
      dockerfile: src/Evently.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    networks:
      - evently_network
  
  evently.database:
    image: postgres:latest
    container_name: Evently.Database
    environment:
      - POSTGRES_DB=evently
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - evently-database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - evently_network

networks:
  evently_network:
    driver: bridge

volumes:
  evently-database-data: